### ISSUE TITLE
Support for Python 3.11

### ISSUE THREAD

**Issue by hacker-DOM** [Ackee-Blockchain/woke#170]
# 3.11 support:

Error see below

web3.py has support https://github.com/ethereum/web3.py/issues/2704
eth_abi added support recently https://github.com/ethereum/eth-abi/pull/194

I think it was recently pre-released (https://pypi.org/project/eth-abi/#history) as 4.0, we’re curently using 3.x

I would wait until all packages have proper releases, then update our requirements. Until then use 3.10

Current error:

```
❯ woke --help
Traceback (most recent call last):
  File "/Users/dteiml/.local/bin/woke", line 5, in <module>
    from woke.cli.__main__ import main
  File "/Users/dteiml/.local/pipx/venvs/woke/lib/python3.11/site-packages/woke/cli/__main__.py", line 20, in <module>
    from .fuzz import run_fuzz
  File "/Users/dteiml/.local/pipx/venvs/woke/lib/python3.11/site-packages/woke/cli/fuzz.py", line 14, in <module>
    from woke.testing.fuzzer import fuzz
  File "/Users/dteiml/.local/pipx/venvs/woke/lib/python3.11/site-packages/woke/testing/fuzzer.py", line 29, in <module>
    from woke.testing.contract import dev_interface
  File "/Users/dteiml/.local/pipx/venvs/woke/lib/python3.11/site-packages/woke/testing/contract.py", line 26, in <module>
    import eth_abi
  File "/Users/dteiml/.local/pipx/venvs/woke/lib/python3.11/site-packages/eth_abi/__init__.py", line 3, in <module>
    from eth_abi.abi import (  # NOQA
  File "/Users/dteiml/.local/pipx/venvs/woke/lib/python3.11/site-packages/eth_abi/abi.py", line 1, in <module>
    from eth_abi.codec import (
  File "/Users/dteiml/.local/pipx/venvs/woke/lib/python3.11/site-packages/eth_abi/codec.py", line 16, in <module>
    from eth_abi.decoding import (
  File "/Users/dteiml/.local/pipx/venvs/woke/lib/python3.11/site-packages/eth_abi/decoding.py", line 14, in <module>
    from eth_abi.base import (
  File "/Users/dteiml/.local/pipx/venvs/woke/lib/python3.11/site-packages/eth_abi/base.py", line 7, in <module>
    from .grammar import (
  File "/Users/dteiml/.local/pipx/venvs/woke/lib/python3.11/site-packages/eth_abi/grammar.py", line 4, in <module>
    import parsimonious
  File "/Users/dteiml/.local/pipx/venvs/woke/lib/python3.11/site-packages/parsimonious/__init__.py", line 9, in <module>
    from parsimonious.grammar import Grammar, TokenGrammar
  File "/Users/dteiml/.local/pipx/venvs/woke/lib/python3.11/site-packages/parsimonious/grammar.py", line 14, in <module>
    from parsimonious.expressions import (Literal, Regex, Sequence, OneOf,
  File "/Users/dteiml/.local/pipx/venvs/woke/lib/python3.11/site-packages/parsimonious/expressions.py", line 9, in <module>
    from inspect import getargspec
ImportError: cannot import name 'getargspec' from 'inspect' (/usr/local/Cellar/python@3.11/3.11.0/Frameworks/Python.framework/Versions/3.11/lib/python3.11/inspect.py)
```

**Comment by michprev** [comment]
Done :white_check_mark:
