### ISSUE TITLE
`woke` process crashing repeatedly

### ISSUE THREAD

**Issue by jmhickman** [Ackee-Blockchain/woke#180]
I see there is a lot of commit activity in this repo, so I'm not sure if the source of these crashes has been resolved already vs the 1.3.1 version already available.

I'm using the VSCode addon, this is a sample of the errors in the output tab.

I'm using the remote dev functionality of VSCode, so `woke` is running in a remote linux environment.

```
[Error - 9:42:18 PM] Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/server.py", line 259, in _task_done_callback
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/lsp_compiler.py", line 178, in run
    await self.__compilation_loop()
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/lsp_compiler.py", line 872, in __compilation_loop
    await self.__compile(
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/lsp_compiler.py", line 775, in __compile
    self.__ir_reference_resolver.run_post_process_callbacks(
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/reference_resolver.py", line 96, in run_post_process_callbacks
    callback(callback_params)
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/meta/identifier_path.py", line 70, in _post_process
    assert isinstance(referenced_declaration, DeclarationAbc)
AssertionError

[Info  - 9:42:18 PM] Connection to server got closed. Server will restart.
Running 'woke lsp --port 38045'
[Error - 9:45:19 PM] Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/server.py", line 259, in _task_done_callback
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/lsp_compiler.py", line 178, in run
    await self.__compilation_loop()
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/lsp_compiler.py", line 872, in __compilation_loop
    await self.__compile(
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/lsp_compiler.py", line 754, in __compile
    self.__source_units[path] = SourceUnit(init, ast)
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/meta/source_unit.py", line 112, in __init__
    self._contracts.append(ContractDefinition(init, node, self))
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/declaration/contract_definition.py", line 141, in __init__
    self._functions.append(FunctionDefinition(init, node, self))
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/declaration/function_definition.py", line 168, in __init__
    OverrideSpecifier(init, function.overrides, self)
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/meta/override_specifier.py", line 75, in __init__
    self._overrides.append(IdentifierPath(init, override, self))
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/meta/identifier_path.py", line 175, in __init__
    assert groups_count > 0
AssertionError

[Info  - 9:45:19 PM] Connection to server got closed. Server will restart.
Running 'woke lsp --port 33469'
Command failed: woke lsp --port 38045

Command failed: woke lsp --port 38393

[Error - 9:46:35 PM] Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/server.py", line 259, in _task_done_callback
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/lsp_compiler.py", line 178, in run
    await self.__compilation_loop()
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/lsp_compiler.py", line 852, in __compilation_loop
    await self.__compile(self.__discovered_files)
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/lsp_compiler.py", line 775, in __compile
    self.__ir_reference_resolver.run_post_process_callbacks(
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/reference_resolver.py", line 96, in run_post_process_callbacks
    callback(callback_params)
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/meta/identifier_path.py", line 70, in _post_process
    assert isinstance(referenced_declaration, DeclarationAbc)
AssertionError
```

**Comment by jmhickman** [comment]
Just had this happen. Not sure if related to previous crashes or not:

```
[Info  - 7:39:12 PM] Connection to server got closed. Server will restart.
Running 'woke lsp --port 36867'
[Error - 7:42:22 PM] Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/server.py", line 259, in _task_done_callback
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/lsp_compiler.py", line 178, in run
    await self.__compilation_loop()
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/lsp_compiler.py", line 872, in __compilation_loop
    await self.__compile(
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/lsp_compiler.py", line 754, in __compile
    self.__source_units[path] = SourceUnit(init, ast)
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/meta/source_unit.py", line 112, in __init__
    self._contracts.append(ContractDefinition(init, node, self))
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/declaration/contract_definition.py", line 141, in __init__
    self._functions.append(FunctionDefinition(init, node, self))
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/declaration/function_definition.py", line 165, in __init__
    self._body = Block(init, function.body, self) if function.body else None
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/statement/block.py", line 57, in __init__
    self._statements = [
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/statement/block.py", line 58, in <listcomp>
    StatementAbc.from_ast(init, statement, self)
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/statement/abc.py", line 103, in from_ast
    return VariableDeclarationStatement(init, statement, parent)
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/statement/variable_declaration_statement.py", line 64, in __init__
    self._declarations.append(VariableDeclaration(init, declaration, self))
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/declaration/variable_declaration.py", line 170, in __init__
    self._type_name = TypeNameAbc.from_ast(
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/type_name/abc.py", line 87, in from_ast
    return UserDefinedTypeName(init, type_name, parent)
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/type_name/user_defined_type_name.py", line 139, in __init__
    self._path_node = IdentifierPath(
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/meta/identifier_path.py", line 175, in __init__
    assert groups_count > 0
AssertionError

[Info  - 7:42:22 PM] Connection to server got closed. Server will restart.
Running 'woke lsp --port 45291'
[Error - 7:42:36 PM] Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/server.py", line 259, in _task_done_callback
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/lsp_compiler.py", line 178, in run
    await self.__compilation_loop()
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/lsp_compiler.py", line 852, in __compilation_loop
    await self.__compile(self.__discovered_files)
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/lsp_compiler.py", line 754, in __compile
    self.__source_units[path] = SourceUnit(init, ast)
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/meta/source_unit.py", line 112, in __init__
    self._contracts.append(ContractDefinition(init, node, self))
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/declaration/contract_definition.py", line 141, in __init__
    self._functions.append(FunctionDefinition(init, node, self))
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/declaration/function_definition.py", line 165, in __init__
    self._body = Block(init, function.body, self) if function.body else None
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/statement/block.py", line 57, in __init__
    self._statements = [
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/statement/block.py", line 58, in <listcomp>
    StatementAbc.from_ast(init, statement, self)
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/statement/abc.py", line 103, in from_ast
    return VariableDeclarationStatement(init, statement, parent)
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/statement/variable_declaration_statement.py", line 64, in __init__
    self._declarations.append(VariableDeclaration(init, declaration, self))
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/declaration/variable_declaration.py", line 170, in __init__
    self._type_name = TypeNameAbc.from_ast(
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/type_name/abc.py", line 87, in from_ast
    return UserDefinedTypeName(init, type_name, parent)
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/type_name/user_defined_type_name.py", line 139, in __init__
    self._path_node = IdentifierPath(
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/meta/identifier_path.py", line 175, in __init__
    assert groups_count > 0
AssertionError

[Info  - 7:42:36 PM] Connection to server got closed. Server will restart.
Running 'woke lsp --port 37581'
[Error - 7:42:49 PM] Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/server.py", line 259, in _task_done_callback
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/lsp_compiler.py", line 178, in run
    await self.__compilation_loop()
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/lsp_compiler.py", line 852, in __compilation_loop
    await self.__compile(self.__discovered_files)
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/lsp_compiler.py", line 754, in __compile
    self.__source_units[path] = SourceUnit(init, ast)
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/meta/source_unit.py", line 112, in __init__
    self._contracts.append(ContractDefinition(init, node, self))
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/declaration/contract_definition.py", line 141, in __init__
    self._functions.append(FunctionDefinition(init, node, self))
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/declaration/function_definition.py", line 168, in __init__
    OverrideSpecifier(init, function.overrides, self)
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/meta/override_specifier.py", line 75, in __init__
    self._overrides.append(IdentifierPath(init, override, self))
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/meta/identifier_path.py", line 175, in __init__
    assert groups_count > 0
AssertionError

[Info  - 7:42:49 PM] Connection to server got closed. Server will restart.
Running 'woke lsp --port 33127'
[Error - 7:43:03 PM] Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/server.py", line 259, in _task_done_callback
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/lsp_compiler.py", line 178, in run
    await self.__compilation_loop()
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/lsp_compiler.py", line 852, in __compilation_loop
    await self.__compile(self.__discovered_files)
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/lsp_compiler.py", line 754, in __compile
    self.__source_units[path] = SourceUnit(init, ast)
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/meta/source_unit.py", line 112, in __init__
    self._contracts.append(ContractDefinition(init, node, self))
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/declaration/contract_definition.py", line 141, in __init__
    self._functions.append(FunctionDefinition(init, node, self))
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/declaration/function_definition.py", line 165, in __init__
    self._body = Block(init, function.body, self) if function.body else None
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/statement/block.py", line 57, in __init__
    self._statements = [
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/statement/block.py", line 58, in <listcomp>
    StatementAbc.from_ast(init, statement, self)
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/statement/abc.py", line 103, in from_ast
    return VariableDeclarationStatement(init, statement, parent)
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/statement/variable_declaration_statement.py", line 64, in __init__
    self._declarations.append(VariableDeclaration(init, declaration, self))
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/declaration/variable_declaration.py", line 170, in __init__
    self._type_name = TypeNameAbc.from_ast(
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/type_name/abc.py", line 87, in from_ast
    return UserDefinedTypeName(init, type_name, parent)
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/type_name/user_defined_type_name.py", line 139, in __init__
    self._path_node = IdentifierPath(
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/meta/identifier_path.py", line 175, in __init__
    assert groups_count > 0
AssertionError

[Info  - 7:43:03 PM] Connection to server got closed. Server will restart.
Running 'woke lsp --port 46517'
[Error - 7:43:17 PM] Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/server.py", line 259, in _task_done_callback
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/lsp_compiler.py", line 178, in run
    await self.__compilation_loop()
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/lsp_compiler.py", line 852, in __compilation_loop
    await self.__compile(self.__discovered_files)
  File "/usr/local/lib/python3.10/dist-packages/woke/lsp/lsp_compiler.py", line 754, in __compile
    self.__source_units[path] = SourceUnit(init, ast)
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/meta/source_unit.py", line 112, in __init__
    self._contracts.append(ContractDefinition(init, node, self))
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/declaration/contract_definition.py", line 141, in __init__
    self._functions.append(FunctionDefinition(init, node, self))
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/declaration/function_definition.py", line 165, in __init__
    self._body = Block(init, function.body, self) if function.body else None
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/statement/block.py", line 57, in __init__
    self._statements = [
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/statement/block.py", line 58, in <listcomp>
    StatementAbc.from_ast(init, statement, self)
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/statement/abc.py", line 103, in from_ast
    return VariableDeclarationStatement(init, statement, parent)
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/statement/variable_declaration_statement.py", line 64, in __init__
    self._declarations.append(VariableDeclaration(init, declaration, self))
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/declaration/variable_declaration.py", line 170, in __init__
    self._type_name = TypeNameAbc.from_ast(
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/type_name/abc.py", line 87, in from_ast
    return UserDefinedTypeName(init, type_name, parent)
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/type_name/user_defined_type_name.py", line 139, in __init__
    self._path_node = IdentifierPath(
  File "/usr/local/lib/python3.10/dist-packages/woke/ast/ir/meta/identifier_path.py", line 175, in __init__
    assert groups_count > 0
AssertionError

[Error - 7:43:17 PM] The Tools for Solidity server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```
