### ISSUE TITLE
woke 3.4.0 crashes language server immediately on all repos

### ISSUE THREAD

**Issue by DrakeEvans** [Ackee-Blockchain/woke#242]
This is the traceback I receive on this (woke) repository:

[Error - 11:44:09 AM] Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/woke/lsp/server.py", line 268, in _task_done_callback
    task.result()
  File "/opt/homebrew/lib/python3.11/site-packages/woke/lsp/lsp_compiler.py", line 185, in run
    await self.__compilation_loop()
  File "/opt/homebrew/lib/python3.11/site-packages/woke/lsp/lsp_compiler.py", line 905, in __compilation_loop
    await self.__compile(self.__discovered_files)
  File "/opt/homebrew/lib/python3.11/site-packages/woke/lsp/lsp_compiler.py", line 834, in __compile
    p.start()
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_asyncio.Task' object

**Comment by michprev** [comment]
Thank you for reporting this. Should be fixed in 3.4.1, can you confirm it, please?

**Comment by DrakeEvans** [comment]
Working now thank you, love woke and tools for solidity.  Appreciate all your work and responsiveness
